### ISSUE TITLE
[PS Vita] Klonoa - Empire of Dreams (USA) - Crash while exiting level 1-3

### ISSUE THREAD

**Issue by 16BitWonder** [libretro/vba-next#100]
After exiting the door (completing the level) in the third level of the first world, the image fades out normally, freezes and then crashes.

I had this happen once, wiped the save and tried again, then tried going through the door without having collected all of the items and the crash occurred all three times.

I've attached the three crash-logs that were generated. Hope they can help.

[Klonoa-[1-3]-Crashes.zip](https://github.com/libretro/vba-next/files/2088460/Klonoa-.1-3.-Crashes.zip)

**Comment by negativeExponent** [comment]
anyone can confirm this? and when it happens can upload the save data near the affected aread? i think savestates should help too (hope vita saves are compatible with x68 pc)

**Comment by 16BitWonder** [comment]
I tested it again with a fully updated setup; latest VBA-Next+Retroarch on Vita and it no longer appears to be crashing at 1-3.

It could be that I had a bad dump or commits since then have fixed the issue.
In either case it seems to be working now.
