### ISSUE TITLE
Jurassic Park III: Park Builder - Unreadable text

### ISSUE THREAD

**Issue by Oggom** [libretro/vba-next#12]
VBA-Next has issues displaying the text in Jurassic Park III: Park Builder making it unreadable.
This problem is not present in vanilla VBA (tested both 1.7.2 and 1.8.0 beta 3).

**Comment by retro-wertz** [comment]
i confirm this, in 2019... probably related to issue posted about other games like golden sun having no effects.

**Comment by negativeExponent** [comment]
this should be fixed when PR is merged

(before and after pics):
![Screenshot_2019-09-07_06-23-54](https://user-images.githubusercontent.com/54053706/64464649-51f81800-d13b-11e9-9db2-f16853fbb4de.png)
![Screenshot_2019-09-07_06-22-47](https://user-images.githubusercontent.com/54053706/64464653-56bccc00-d13b-11e9-8596-21681d17a7d2.png)
