### ISSUE TITLE
Hamtaro: Ham-Ham Games

### ISSUE THREAD

**Issue by Oggom** [libretro/vba-next#13]
I found a small bug in Hamtaro: Ham-Ham Games:
If you don't skip the developer logos at the beginning of the game it will get stuck at a black screen.
This doesn't happen in VBA-M.

**Comment by retro-wertz** [comment]
i cant replicate this on latest version (linux)

**Comment by hizzlekizzle** [comment]
Ok, I'll close this then. If anyone else can reproduce it, feel free to reopen the issue.

**Comment by Oggom** [comment]
I just gave it a try, it's still happening on my end with the latest nightly build on Windows.

**Comment by retro-wertz** [comment]
@Oggom  so only on windows? let me know if it still does...

**Comment by Oggom** [comment]
It looks like the current nightly builds are out of date and miss several commits. I give it another try when it's building again.

**Comment by Oggom** [comment]
Alright, looks like someone fixed the buildbot as it's building again now.

The glitch seems to no longer appear in the current nightly build.

**Comment by retro-wertz** [comment]
thats great news. thanks for testing.
