### ISSUE TITLE
Metal Slug Advance - Input Crash

### ISSUE THREAD

**Issue by Oggom** [libretro/vba-next#14]
Metal Slug Advance crashes/freezes when pressing left + right + B (shoot).

Apparently the game is unable to handle such input, since it's technically not possible to press left and right at the same time on real hardware without any modifications.

VBA-M mainline doesn't allow pressing both directions at the same time by default, but there is no such option in RetroArch.

The same problem also exists in VBA-M libretro and possibly in the Meteor and Mednafen GBA ports as well, but I'm unable to progress far enough into the game on those cores.

There has been an attempt to fix it with https://github.com/libretro/vba-next/commit/9a259d4866bf28114e386625400528fa5539e65c but it doesn't seem to be working.

**Comment by negativeExponent** [comment]
this should be fixed in latest commit
