### ISSUE TITLE
Abrupt exit/crash running PD ROM Space Loonies under Android RetroArch

### ISSUE THREAD

**Issue by Bargaintuan** [libretro/vba-next#18]
I get this crash 100% of the time in the Space Loonies title screen, but only in RetroArch Android. It is most likely caused by the BG2X and BG2Y registers becoming negative, which is perfectly legal on hardware. It works fine on hardware, in VBA-M, and in VBA-Next on Win32. If you start a game before the point at which the title crashes, it plays fine until the game ends and it shows the title screen again.

Here is the section of source where the game crashes:

```
  REG16(REG_BG2CNT) = 0;
  REG32(REG_DISPCNT) = 
    DISPCNT_BG_MODE(4) + DISPCNT_ENABLE_BG(2) +
    DISPCNT_ENABLE_OBJ + DISPCNT_1D_OBJ_MAPPING;
  for(i = 128; i < 512; i += 4) {
    REG16(REG_BG2PA) = i;
    REG16(REG_BG2PB) = 0;
    REG16(REG_BG2PC) = 0;
    REG16(REG_BG2PD) = i;
    REG32(REG_BG2X) = (120 << 8) - i * 120;
    REG32(REG_BG2Y) = (43 << 8) - i * 43;
    if(IsKeyClicked(KEY_START | KEY_A)) return 1;
    DittyPlayJiffy();
    r250();
    while((REG32(REG_DISPSTAT) & DISPSTAT_VBLANK) != 0);
    CheckReset();
    while((REG32(REG_DISPSTAT) & DISPSTAT_VBLANK) == 0) Halt();
  }
```

The game runs through this loop for a second or two before the crash, so I strongly suspect the crash is dependent on the value of i. It looks very much like the crash happens when the background is 1:1 scale, which would make i > 256 and cause BG2X and BG2Y to be set negative.

The ROM is in the public domain and can be downloaded at http://www.bargaintuan.com/gba/Space_Loonies.zip

I hope this information will help solve problems with other ROMs as well.

**Comment by retro-wertz** [comment]
i cant replicate this on latest version (android 5.1 arm7a )

**Comment by hizzlekizzle** [comment]
Ok, I'll close this then. If anyone else can reproduce it, feel free to reopen the issue.
