### ISSUE TITLE
GBC Sound Channel 3 issues on GBA

### ISSUE THREAD

**Issue by Bargaintuan** [libretro/vba-next#19]
GBC Sound Channel 3 sounds very wrong in VBA-Next in RetroArch running GBA ROMs on Android and Win32. VBA-M sounds correct. Not sure what is going on, but it sounds _very_ wrong. My guess is that it's not handling the update of the wave data correctly, which the player code does to simulate the envelope settings of the other channels. I tested this in my GBA tracker to confirm the issue. It can be found at http://www.bargaintuan.com/misc/dittyedtest.zip with the source code to the player and a save from Win32 with a simple track. Of course, make sure the GBA file and the SRM file are in the same directory for testing.

Once in the editor, press Start and select LOAD from the FILE menu with the d-pad and A button. Press Start again, this time selecting ONCE from the PLAY menu. The editor should then play three notes. The three notes should sound very similar (and do on hardware and in VBA-M) but in VBA-Next, the third note sounds nothing like the other two.

It's possible that the code is treating Sound 3 as if it's an actual GBC channel, but there are enhancements to this channel on the GBA. Specifically, the 32-sample wave bank has been expanded to 64 samples, which can be treated as one large buffer or as two 32-sample buffers, allowing the data to be double-buffered and thus freeing it of some of the glitches present on the GBC. Info on how Sound 3 should work on the GBA is here: http://belogic.com/gba/

**Comment by retro-wertz** [comment]
this should sound better in latest commits....

**Comment by hizzlekizzle** [comment]
ok, gonna close this, then. Feel free to reopen if something changes.
