### ISSUE TITLE
(Wii) 32MB games crash to hbc

### ISSUE THREAD

**Issue by SuperrSonic** [libretro/vba-next#30]
It was still working in the September 22 commit.

**Comment by twinaphex** [comment]
Could be that RetroArchs binary size is getting to be too big so that 32MB ROM games no longer fit into memory. Wed have to start looking at which parts of RA we can do without on RAM-deficient devices like the Wii.

**Comment by SuperrSonic** [comment]
I had not thought of that because there are other cores which are way bigger and run bigger ROMs.
Because of this I didn't actually check but the change in size from the VBA Next commit from Sep 22 and the current source should be negligible.
