### ISSUE TITLE
(iOS) After this commit 0b7b177a8, sound crackling appeared.

### ISSUE THREAD

**Issue by netux79** [libretro/vba-next#32]
I have just compiled the new version of the core for iOS and during some games a weird sound cracking appeared that was not present in previous version.

I have not tested on other platforms yet.

It all started on 0b7b177a8 commit.

**Comment by twinaphex** [comment]
Hmm, I guess we should revert those Bizhawk-derived changes then. I assumed it was for the better.

**Comment by netux79** [comment]
Tested again after the revert and it is now working fine... thanks!
