### ISSUE TITLE
RetroArch Wii VBA Next crashes at certain points in certain games

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/vba-next#39]
RetroArch Wii version - 1.3.2

Homebrew Channel version - 1.1.0

Wii version - 4.3U

So far two games I have played on the VBA Next emulator for the Wii that I am having issues with are as follows:

Mega Man Zero 2: When I enter the boss room at the Temple of Wind, a DSI exception error occurs and the whole thing reboots.

Castlevania: Harmony of Dissonance: In the Skeleton Cave, I enter a certain room and the screen goes black, freezes up, and makes a whistling sound.
**UPDATE** - A DSI error occurs when I hit the Bronze armor with the giant hammer in the Clock Tower.

I don't know what the problem could be.  I would use mGBA since it moves faster than VBA Next but it doesn't have cheat support yet.  Please help me, I'm going crazy!  If I have any similar issues with other games I will let you know!

**Comment by dagreatbuzzsaw** [comment]
I should also note that when these crashes happen and I reboot, when I return to the game I find that the save has reverted to the last save I made before I first turned the game on.  Any saves I made between then and when the game crashed were deleted and reverted to said last save.  This is frustrating if you played for a long time only for the game to crash and all that work was gone.

**Comment by fr500** [comment]
saves are flushed on exit so that's perfectly normal in a crash event

**Comment by retro-wertz** [comment]
sounds like issue is similar to this
https://github.com/libretro/vba-next/issues/93

this should be working now in latest commits.
