### ISSUE TITLE
Achievements unlock when game starts includes Log

### ISSUE THREAD

**Issue by grenade44** [libretro/vba-next#59]
Some achievements unlock when game starts, I found this on some games or achievements dont unlock at all. 

I also found out that GBA memory vaules change everytime you load the game,(Not sure if this is the case for all GBA games). so i know some game achievements have been made from there music IDs. Im not sure if thats the case with this Crash game but I know all pokemon games for GBA use music IDs.

**Log**
RetroArch [INFO] :: Redirecting save file to "/home/pi/RetroPie/roms/gba/Crash Bandicoot.srm".
RetroArch [INFO] :: === Build =======================================
Capabilities: 
Built: Jul 17 2016
RetroArch [INFO] :: Version: 1.3.6
RetroArch [INFO] :: Git: 7a433a6
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Config: appending config "/tmp/retroarch.cfg"
RetroArch [INFO] :: Config: loading config from: /opt/retropie/configs/gba/retroarch.cfg.
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Loading dynamic libretro core from: "/home/pi/vba-next2/vba_next_libretro.so"
RetroArch [INFO] :: Overrides: no core-specific overrides found at /home/pi/.config/retroarch/config/VBA Next/VBA Next.cfg.
RetroArch [INFO] :: Overrides: no game-specific overrides found at /home/pi/.config/retroarch/config/VBA Next/Crash Bandicoot.cfg.
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: remap directory: /opt/retropie/configs/gba/
RetroArch [INFO] :: Remaps: no game-specific remap found at /opt/retropie/configs/gba/VBA Next/Crash Bandicoot.rmp.
RetroArch [INFO] :: Remaps: no core-specific remap found at /opt/retropie/configs/gba/VBA Next/VBA Next.rmp.
RetroArch [INFO] :: Redirecting save file to "/home/pi/RetroPie/roms/gba/Crash Bandicoot.srm".
RetroArch [INFO] :: Environ GET_CAN_DUPE: true
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [libretro INFO] :: Frontend supports RGB565 - will use that instead of XRGB1555.
RetroArch [INFO] :: Environ PERFORMANCE_LEVEL: 10.
RetroArch [INFO] :: Loading content file: /home/pi/RetroPie/roms/gba/Crash Bandicoot.GBA.
RetroArch [INFO] :: Did not find a valid content patch.
RetroArch [INFO] :: CRC32: 0xf1d06a0 .
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] ::     RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] ::     RetroPad, User 1, Button "Select" => "Select"
RetroArch [INFO] ::     RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] ::     RetroPad, User 1, Button "A (right)" => "A"
RetroArch [INFO] ::     RetroPad, User 1, Button "L" => "L"
RetroArch [INFO] ::     RetroPad, User 1, Button "R" => "R"
RetroArch [libretro INFO] :: GameID in ROM is: AC8P
RetroArch [libretro INFO] :: RTC = 0.
RetroArch [libretro INFO] :: flashSize = 65536.
RetroArch [libretro INFO] :: cpuSaveType = 0.
RetroArch [libretro INFO] :: mirroringEnable = 0.
RetroArch [INFO] :: CHEEVOS testing NES (discards VROM)
RetroArch [INFO] :: CHEEVOS testing Generic (plain content)
RetroArch [INFO] :: CHEEVOS getting game id for hash 03beecd053b2ddf56341a6a981c561fc
RetroArch [INFO] :: CHEEVOS got game id 5535
RetroArch [INFO] :: CHEEVOS got achievements for game id 5535
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 32146.00 Hz.
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/2xScaleHQ.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_lanczos4.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_snes.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/Brighter-with_Contrast.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/bsnes_gamma_ramp.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi-curvature-vertical.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi-curvature.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi-vertical.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gameboy-screen-grid.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gameboy.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gameboy2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x&lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2xwaterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2xwaterpaintscanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq4x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq4x_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/nds.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/nedi.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpainthicontrast.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpaintscanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_scanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_waterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/stock.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/xbr-lv1-noblend.glslp"
RetroArch [INFO] :: Video @ 720x480
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 720x480.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: OES_texture_npot => exists
RetroArch [INFO] :: Querying GL extension: BGRA8888 => exists
RetroArch [WARN] :: [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
RetroArch [INFO] :: Querying GL extension: GL_EXT_unpack_subimage => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_sRGB => doesn't exist
RetroArch [INFO] :: GL: Using resolution 720x480
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 1024 frames
RetroArch [INFO] :: ALSA: Buffer size: 2048 frames
RetroArch [INFO] :: null: [/opt/retropie/configs/gba/content_history.lpl].
RetroArch [INFO] :: CHEEVOS posted playing game 5535 activity
RetroArch [INFO] :: CHEEVOS awarding cheevo 30444: Slidin' Through Egypt (Get a platinum relic in Slip-n-Slidin' Sphinx.)
RetroArch [INFO] :: CHEEVOS awarded achievement 30444
RetroArch [INFO] :: CHEEVOS awarding cheevo 30436: From The Grave To Your Plate (Get a platinum relic in Hoppin' Coffins.)
RetroArch [INFO] :: CHEEVOS awarded achievement 30436
RetroArch [INFO] :: CHEEVOS awarding cheevo 30431: Speedipus-Rex (Get a platinum relic in Lagoony Tunes.)
RetroArch [INFO] :: CHEEVOS awarded achievement 30431
RetroArch [INFO] :: CHEEVOS awarding cheevo 30462: You Sure Blue It (Reconstruct the blue gem by acquiring all four shards.)
RetroArch [INFO] :: CHEEVOS awarded achievement 30462
RetroArch [INFO] :: CHEEVOS awarding cheevo 30453: Ahead In The Game (Hold 30 lives at one time.)
RetroArch [ERROR] :: [http] Could not create new HTTP session handle.
RetroArch [ERROR] :: CHEEVOS error awarding achievement 30453, retrying
RetroArch [INFO] :: CHEEVOS awarded achievement 30453
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => doesn't exist
RetroArch [INFO] :: Saving RAM type #0 to "/home/pi/RetroPie/roms/gba/Crash Bandicoot.srm".
RetroArch [INFO] :: Saved successfully to "/home/pi/RetroPie/roms/gba/Crash Bandicoot.srm".
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [libretro INFO] :: [VBA] Sync stats: Audio frames: 5724154, Video frames: 10685, AF/VF: 535.72
RetroArch [INFO] :: Average audio buffer saturation: 11.93 %, standard deviation (percentage points): 18.21 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 92.26 %. Close to blocking: 1.86 %.
RetroArch [INFO] :: Threaded video stats: Frames pushed: 12574, Frames dropped: 0.
RetroArch [INFO] :: Monitor FPS estimation is disabled for threaded video.
RetroArch [INFO] :: Average audio buffer saturation: 11.93 %, standard deviation (percentage points): 18.21 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 92.26 %. Close to blocking: 1.86 %.
RetroArch [INFO] :: Monitor FPS estimation is disabled for threaded video.

**Comment by leiradel** [comment]
@grenade44 there were a lot of fixes to the achievements in RetroArch these days, could you try again with a nightly build?

Thanks.

**Comment by grenade44** [comment]
I've tested with your nightly and it seems to have fixed the problem. I think we can close this issue now.
