### ISSUE TITLE
(PS VITA) - Golden Sun (S)(Independent) - Crash Invoke Djinn

### ISSUE THREAD

**Issue by rymexs** [libretro/vba-next#78]
Hi! The crash occurs with the last nightly. During a battle invoking a Djinn, this one executes its attack, in the end it will show the damage to each enemy and then retroarch sends error message.

Attached is the crash dump generated by the emulator.

Thanks!
[PsVita_VBANext_Crash.zip](https://github.com/libretro/vba-next/files/611236/PsVita_VBANext_Crash.zip)

**Comment by retro-wertz** [comment]
i dont know how to read the dump file :D anyone with Vita able to reproduce with latest vba_next version?

**Comment by rymexs** [comment]
This issue has been fixed https://github.com/libretro/vba-next/issues/104
