### ISSUE TITLE
Crash on Castlevania Aria of Sorrow

### ISSUE THREAD

**Issue by darklinkpower** [libretro/vba-next#8]
- I'm playing Castlevania Aria of Sorrow from GBA and it plays perfectly but it crashes when either:
  I hit an enemy and it's "die" animation has too much effects or i kill two enemies at the same time( medusa heads) although the last one seems too happen only in one location.
  I have tried changing the emulator settings such as shaders,  custom zoom, etc. but nothing seems to work.

**Comment by retro-wertz** [comment]
ive been running a few playthroughs now with this game using this core, and on latest release, i dont seem to have any issue, crashing or graphics wise or any other noticeable problems.

**Comment by hizzlekizzle** [comment]
ok, gonna close this, then. Feel free to reopen if something changes.
