### ISSUE TITLE
Crash on ending cutscene in Castlevania: Aria of Sorrow.

### ISSUE THREAD

**Issue by Blueshirtt** [libretro/vba-next#80]
Consistent every time. Loaded multiple times, crashes each time at exact frame. PC, latest nightly as of 2/27.

![rarch](https://cloud.githubusercontent.com/assets/7568077/23361919/b90fad00-fcb8-11e6-9088-a0cabc655280.PNG)

**Comment by Yoshideking** [comment]
I wasn't aware of this bug being a RetroArch thing. Cuz this very same bug is my test to see the advances on the VBA Next core in PS Vita. It crushes in there too, but every time I update RA, I can see new frames of the castle's explotion, so that gives me the feel that the project is ongoing.

I'm cheering for your work RA Team!

**Comment by treyjazz** [comment]
It crashes on the gpSP core too. I am running it on a recent Vita nightly - v1.0.2e773475 of VBA Next core. Since it happens with both cores it is either common code between the two or RA itself. Note that it makes it to just after the burst when the screen is (nearly?) blank.

**Comment by retro-wertz** [comment]
to everyone still or has been affected with this issue --- can you guys test with latest commit? i have completed a few runs of aria of sorrow but i dont have this crash issue with latest updates, but probably there are some cases which can cause this crash (if ever it still happens) please post savestate before the crash if possible.

**Comment by Yoshideking** [comment]
I just updated RetroArch. Thanks dude. Really!
And I think GBA runs smoothly overall. I was on 1.7.1 and it fells like the sound runs better! Gonna test Advance wars to confirm this.

Keep it great!

**Comment by retro-wertz** [comment]
thanks for the confirmation.
