### ISSUE TITLE
Hamtaro Rainbow Rescue (E) crash (segfault)

### ISSUE THREAD

**Issue by maxlefou** [libretro/vba-next#82]
A complete crash of RetroArch occurs when playing a certain minigame in Hamtaro Rainbow Rescue:

- The minigame is the one where Pashmina puts rings around the characters to get points. It's located in the festival level when you're trying to get the color red. Since this minigame is mandatory to progress in the game, it makes the game unfinishable.
- The crash occurs when you start the minigame. It forces RetroArch to exit. The logs just says it's caused by a segfault. [Here's the dumped core](https://pastebin.com/gwefG03u).
- This has been only tested on the european version of the game by Rising Sun, in french language (MD5 checksum : 4a4a77b12b463a758a143642f96b1846) on the linux 1.6.1 version of RetroArch. I don't know if it does it on other versions or on other cores. It's kinda hard to see since it occurs very far in the game

I included [the save of the game](https://github.com/libretro/vba-next/files/1105684/1727.-.Hamtaro.-.Rainbow.Rescue.E.Rising.Sun.zip) for those who wants to try. Once you loaded it, just go up and speak to the hamster at the left, near the sign with a sunflower. Choose Pashmina and start the game.

**Comment by retro-wertz** [comment]
i cant confirm this with latest update. must have been silently fixed with recent commits. i dont understand the language but talking and starting the mini game as instructed does not cause core to crash.

RE:
the posted logfile is related to the same function that causing also some crashes here:
https://github.com/libretro/vba-next/issues/93

**Comment by maxlefou** [comment]
The problem didn't occured again with the version 1.7.3. I guess it got corrected. Closing up.
